# Generated by Django 3.2.4 on 2023-02-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres_cliente', models.CharField(max_length=100)),
                ('apellidos_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(max_length=12)),
                ('correo_cliente', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_producto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.IntegerField()),
                ('fecha_inicio_descuento', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.IntegerField()),
                ('fecha_inicio_descuento', models.DateField()),
                ('fecha_fin_descuento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('codigo_d', models.BigAutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio_sector', models.CharField(max_length=75)),
                ('ciudad', models.CharField(max_length=50)),
                ('departamento_provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tamaño', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres_vendedor', models.CharField(max_length=100)),
                ('apellidos_vendedor', models.CharField(max_length=100)),
                ('telefono_vendedor', models.CharField(max_length=12)),
                ('rut_vendedor', models.CharField(max_length=20)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres_proveedor', models.CharField(max_length=100)),
                ('apellidos_proveedor', models.CharField(max_length=100)),
                ('telefono_proveedor', models.CharField(max_length=12)),
                ('correo_proveedor', models.EmailField(max_length=254)),
                ('rut_proveedor', models.CharField(max_length=20)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio_venta_producto', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.categoria')),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaVentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.descuentoventa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.facturaventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.producto')),
            ],
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.vendedor'),
        ),
        migrations.CreateModel(
            name='FacturaCompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.facturacompra')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.descuentocompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.producto')),
            ],
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.proveedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.direccion'),
        ),
    ]
